version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    environment:
      - POSTGRESQL_CONNECTION_STRING=${POSTGRESQL_CONNECTION_STRING}
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=CleanArchitectureExample
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
